### ISSUE TITLE
Possible mistype on Reuse chapter

### ISSUE THREAD

**Issue by tony-jones** [adamsilver/maintainablecss.com-jekyll#12]
On the reuse chapter, near the top, there is this line

"If you **don’t** repeat yourself, then you break semantics. Go read that chapter."

Should this be?

"If you repeat yourself, then you break semantics. Go read that chapter."

If that is the case, I can submit a pull request.

**Comment by adamsilver** [comment]
No, actually this is correct already, but it doesn't read very well. 

I mean if you attempt to reuse the bits inside the curly braces i.e. 

blah { color: red; } by having atomic class names such as .red {} then you break the first rule of MaintainableCSS i.e. everything that I stated in Semantics.

I will try and write this better.

Thank you Tony

**Comment by tony-jones** [comment]
Ah, that makes sense now @adamsilver . Thanks for clarifying!
