### ISSUE TITLE
Difference to BEM CSS?

### ISSUE THREAD

**Issue by kraftwer1** [adamsilver/maintainablecss.com-jekyll#25]
I'm evaluating different methodologies at the moment. As far as I can see, MaintainableCSS shares the basic principles of BEM. Are there any major key differences?

**Comment by davidhellmann** [comment]
In my opinion the difference is how do you write your css. Most of the methodologies are based von DRY and stuff like ATOMIC etc. For me this own here sounds much more simpler to use. Huge respect to Harry — http://csswizardry.com/ — but for me most of the time when I read articles that he write, I'm a bit confused how complex the things are that he recommended.

I think the buzzword here is "maintainable" and in my current project I have a lot of small CSS files for each module. Some of this are really near by each other but they also have a own file and a own naming. 

Modiefiers are cool but I think they worked just for components inside a module well. The modul itself as modifier is not the best I think. 

But just my tow cents :)

**Comment by adamsilver** [comment]
There is a lot of similarity to BEM, and I want to acknowledge this in the book, in another chapter coming soon.

The terminology, some theory/rationale and conventions are different but if you're using BEM, and you're happy, stick with it.
