### ISSUE TITLE
Is it JavaScript or Javascript?

### ISSUE THREAD

**Issue by cjpatoilo** [adamsilver/maintainablecss.com-jekyll#41]
http://maintainablecss.com/chapters/javascript/

I know this isn't programming-related, but I'm curious what you thinks about this subject. The official name is **JavaScript** instead of **Javascript**, though it really doesn't matter in practice. [You can view the documentation here](https://developer.mozilla.org/en-US/docs/Web/JavaScript).

Thanks for attention! BTW beautiful work, congratulations @adamsilver.

**Comment by adamsilver** [comment]
@cjpatoilo Thanks for the message - JavaScript with a capital S is Mozilla's implementation of _ECMAScript_ - you can read more [here](http://pointedears.de/scripts/test/es-matrix/) in the Forword "There is No Javascript" :)
