### ISSUE TITLE
HTML5 tags (header, section,..) as modules without class

### ISSUE THREAD

**Issue by jstorm31** [adamsilver/maintainablecss.com-jekyll#52]
Hi Adam,
This is reaction to your tweet - https://twitter.com/adambsilver/status/740434324323995648.

At current project, this is, how my HTML document looks like:

```
<body>
  <!-- header as a module instead of "<div class="header"> -->
  <header>
    <div class="header-component">...</div>
  </header>

  <!-- main as a module instead of "<div class="main"> -->
  <main>
    <div class="main-component">...</div>
  </main >

  <!-- footer as a module instead of "<div class="footer"> --> 
  <footer>
    <div class="footer-component">...</div>
  </footer >
</body>
```

I don`t use those tags more than once on the page, so I think there is no need to access those elements by class, or is there?

**Comment by adamsilver** [comment]
Because you have used header-component to denote a component withing the header module I would definitely suggest adding a class="header" to it. Otherwise you have what appears to be a component without a module.

Is it a big deal? No.

But that's what I would suggest.

HTH

**Comment by jstorm31** [comment]
Okay, thank you.
