### ISSUE TITLE
What about using 3rd party css tools like Bootstrap or animate.css?

### ISSUE THREAD

**Issue by racoonsmakeokayfriends** [adamsilver/maintainablecss.com-jekyll#55]
These tools use class names to define their appearance. Like `<h1 class="animated infinite bounce">Example</h1>`

Is there anyway these tools can be compatible with MaintainableCSS philosophy?

**Comment by imjakechapman** [comment]
@racoonsmakeokayfriends 

If you are using something like SCSS / LESS / Stylus for CSS preprocessing you could easily extend those classes into your semantic classes for modules.

```
// HTML
<div class="SomeAnimatedModule SomeAnimatedModule-infiniteBounce"></div>

// SCSS
.SomeAnimatedModule {
     @extend .animated;

     &-infiniteBounce {
          @extend .infinite;
          @extend .bounce;
     }
}
```

**Comment by adamsilver** [comment]
@racoonsmakeokayfriends 3rd party libraries like bootstrap and animate.css can't play nicely with MCSS. How could they - they don't know what _your_ site contains?

They only know how you might what something to look or behave.

So you could take the advice given by @imjakechapman or you could do the equivalent without a preprocessor. Copy the rules over.

As a funny example, you could have a colours.css third party library ( I don't advise ):

```
.red { color: red; }
.blue { color: blue; }
```

But you wouldn't use those in your HTML. You would declare those properties in your modules/components CSS definitions:

```
.yourModule {
    color: blue;
}
```

Same applies for everything else really.
