### ISSUE TITLE
Theme based styles

### ISSUE THREAD

**Issue by broken-puppet** [adamsilver/maintainablecss.com-jekyll#56]
Hello,

Please could you help with the following?

**Scenario:**
Imagine your website gives the user the power to change the skin colour e.g. text could be black in one and grey in the other.

How would you handle this without reusing the style?

**Lets say you had a CSS and HTML like this:**

```
.header-siteName { 
    colour: #000; 
}

<div class="header">
    <div class="header-siteName">Site Name</div>
</div>
```

You could use a modifier on each element and remove the above style completely.

```
.header-siteName-blackTxt {
    color: #000;
}

<div class="header">
    <div class="header-siteName header-siteName-blackTxt">Site Name</div>
</div>

.header-siteName-greyTxt {
    color: #AAA;
}

<div class="header">
    <div class="header-siteName header-siteName-greyTxt">Site Name</div>
</div>

```

This is a good approach but is quite heavy on HTML bloat if you add a modifier to lots of elements.

Another idea is to use a modifier on the parent.

```
.header-blackTxt {
    color: #000;
}

<div class="header header-blackTxt">
    <div class="header-siteName">Site Name</div>
</div>

```

This is fine until you start changing background colour. You would need to update the style directly or add a class onto that element.

```
.header-blackBg  .header-siteName {
    background-color: #000;
}

<div class="header header-blackBg">
    <div class="header-siteName">Site Name</div>
</div>

.header-blackBg {
    background-color: #000;
}

<div class="header">
    <div class="header-siteName header-blackBg">Site Name</div>
</div>

```

The latter can cause bloat (if over-used) and the first goes against the one selector rule (ignoring HTML selectors like .element h2)

How is this best handled?

Should a theme style-sheet be created and loaded based on the skin chosen?

You could remove all styles related to the skin and add them to these themes. You would not be re-using them that way. 

Another approach is overriding the CSS but this breaks the MaintainableCSS rule and everything becomes unclean.

For example:

```
**grey-theme.css**

.header-blackBg {
    background-color: #AAA;
}

**black-theme.css**

.header-blackBg {
    background-color: #000;
}

```

This kind of issue could occur if you have two separate sites with the same layout. Everything would be the same but there might be small differences e.g. colour. I have seen multiple sites that do this but its hard to figure out the right way of approaching it.

Thanks for reading :).

Cheers

Patrick

**Comment by adamsilver** [comment]
Great question @Broken-Puppet - thank you for asking!

I haven't thought about this problem since I last built a white-label large scale website for 6 e-commerce websites that just wanted slight differences in styles.

If you want a white-label solution that reuses HTML and JS, then first rule is to not modify the HTML and CSS.

```
/* common style sheet with most of the rules used for all sites */
.header-siteName {
   /* default styles including a default black text*/
 }

/* override style sheet with tweaks such as colour for a specific site, this one has grey text*/
.header-siteName {
   color: #AAA;
 }
```

Let me know if this answers your question suitably :)
