### ISSUE TITLE
State and Modifiers: why are new classes necessary?

### ISSUE THREAD

**Issue by ap** [adamsilver/maintainablecss.com-jekyll#57]
Basically, what makes this…

```css
.myModule-isHidden { display: none }
```

… materially better than this?

```css
.myModule.isHidden { display: none }
```

----

One obvious difference is the same as with components: if you ever declare …

```css
.isHidden { display: none }
```

… then that style will apply to *all* uses of `isHidden`. But in this case, to me that seems a strength rather than a weakness: which `isHidden` *isn’t* going to want to `display: none`? (And if there is one – well, the chained selector has higher specificity than the naked one.)

Note that because the state classes always have the form `isFoo`, it’s easy to have a rule that state classes should never be styled by themselves – outside of a few exceptions. And you can define a convention for where to put these few exceptions. And in any case it’s not hard to search for rules that match on naked `.isFoo`.

Also, you probably want to have two possible prefixes for state classes, `isFoo` and `hasFoo`, both having the same rules.

----

And if that’s all true, it would apply to modifiers also. This will obviously not fly:

```css
.categoryHeader.girls { ... }
```

This `girls` class is much too openly named. We might pick up styles from elsewhere. But this, it seems to me, would work:

```css
.categoryHeader.forGirls { ... }
```

Now it can no longer cross wires with a module called `girls`. For modifier classes, unlike state classes, you probably want to make it an iron rule without exceptions that a naked `forFoo` class shall never be styled anywhere.

As with state, for modifiers you probably want to cordon off another prefix, maybe `inFoo` (e.g. `inGreen`).

----

Is there some drawback in this approach that I am overlooking?

**Comment by oscarotero** [comment]
I'm agree. In fact, in my css style guide I have modifiers that are classes prefixed with `is-` and `has-`: https://github.com/oscarotero/css-style-guide#modifiers and there's some advantages:

* Increase the priority of the selector (because they can be declared combined with the module)
* Allow to add common css properties, like `.is-disabled { pointer-events: none }`, and other specifics for each module, like `.button.is-disabled { opacity: .5 }`.
* It's easier to handle styles with javascript. For example, you can do simply `$(element).toogleClass('is-disabled'); `, no matter what module is being modified

**Comment by adamsilver** [comment]
1. I agree that you could have isBlah because it's unlikely you'll have a module named that. But as I explain somewhat in the chapters about State and Javascript sometimes a state means something different to different modules. For example a disabled basket may have different styles to a disabled link, or a disabled product or a disabled submit button etc.

2. The same cannot be said for modifiers. A modifier could easily be a module.

3. The suggestion to combine classes `.blah.modifier` is problematic because it doesn't have as broad browser support. My philosophy will always be to put users before developers.

But thanks for these quesitons @oscarotero and @ap, I will add some more detail to the guide to explain why.

**Comment by oscarotero** [comment]
> The suggestion to combine classes .blah.modifier is problematic because it doesn't have as broad browser support.

Do you mean IE6? https://kimblim.dk/css-tests/selectors/
I didn't know this guidestyle has support for that "browser" :)

**Comment by ap** [comment]
Of course without chained selectors the whole proposal breaks down. It *hinges* on the fact that `isDisabled` must only ever be styled in chained selectors, never by itself (`.basket.isDisabled{…}` is OK, `.isDisabled{…}` isn’t).

And if there is trouble with the browser support for chained selectors, they’re obviously a no-go, and so the whole proposal is a no-go.

Only, last I knew, the only browser that ever had trouble with chained selectors was IE&#160;6… not exactly a current issue any more. That’s particularly true considering that IE&#160;6 doesn’t support any SSL protocol/cipher combo that is still secure – so on any HTTPS-based site, at least, IE&#160;6 is definitely a bygone concern. (Those users, if they still exist, are already barred from even entering.)

Is there some other browser support issue I’ve been unaware of?

**Comment by adamsilver** [comment]
I don't have specific browsers in my head. That's partly why I use solutions that just work "everywhere". Users > Developers. Perhaps you have a really compelling reason why `.blah.yay` is better than `.blah-yay`?

What **exactly* do you mean by "IE6 are already barred from entry"? Can you give me as much detail with an example as you have on this please?

**Comment by adamsilver** [comment]
> "I didn't know this guidestyle has support for that "browser" :)"

Is it not working in IE6?

**Comment by ap** [comment]
> I don't have specific browsers in my head. That's partly why I use solutions that just work "everywhere".

You have an implicit definition of everywhere that isn’t literally everywhere. I’m stating the obvious, of course, since you already put it in scare quotes yourself. Instinct is a good thing in the moment, but it needs occasional reflection and revisiting the experiences and assumptions that formed it, lest it become superstition. So when you say you prefer techniques that work “everywhere” the question is, where does your “everywhere” end if you actually reflect on it?

Personally I don’t consider an “everywhere” that extends to IE&#160;6 reasonable [in 2017](https://developer.microsoft.com/en-us/microsoft-edge/ie6countdown/)<sup>1</sup>. (And that’s with an “everywhere” that for me still extends to no-JS and even, to an extent, no-CSS circumstances.)

So here’s your good news of the day: you can make use of chained selectors freely. 😊 They were a problem 10 years ago, but only because of IE&#160;6, and IE&#160;6 is no more.

> What *exactly* do you mean by "IE6 are already barred from entry"? Can you give me as much detail with an example as you have on this please?

I mean that IE&#160;6 cannot even *connect* to any site which uses SSL at a level that’s not currently considered insecure. It will fail with an encryption handshake error at best. If your site passes the [Qualys SSL Check](https://www.ssllabs.com/ssltest/) with even a B grade (I think), you won’t be seeing any IE&#160;6 visitors… ever. With a C grade I *think* you still might but that it depends on what you’re getting marked down for. Still, it won’t be too long before getting a C at all will mean you’re shutting out IE&#160;6 too. There’s nowhere for that browser to go but away.

----

1. Yes, that’s a page published by MSFT themselves…

**Comment by adamsilver** [comment]
@ap 

Very interesting, wasn't aware of that, I'd like to see it in action (so that will go on the todo list :) )

I agree that it is good to reflect on these things. And this conversation amongst others have nudged me to reflect once more. 

However, you didn't respond to "Perhaps you have a really compelling reason why .blah.yay is better than .blah-yay?" which may influence these reflections :)

**Comment by adamsilver** [comment]
Also, are we sure that IE6 is the only affected browser?

**Comment by ap** [comment]
I cannot categorically state that IE&#160;6 is the only affected browser, though I am sure that it is the case.

The problem is that the CSS spec does not set out any particular term for a simple selector that matches more than one element property – it simply implicitly assumes that every simple selector can potentially consist of multiple… property selectors, or whatever you would call the simplest atomic element of a selector. The spec in fact reuses the term “selector” for multiple pieces that an overall selector can be broken down to.

As a result, it is impossible to google specifically for facts related to these issues, because the terminology is ambiguous. “Chained selectors” is about as precise a term for this as there is, but even that is not official.

In fact, this implicit assumption that *of course every simple selector can match on multiple classes* in the spec goes further: even the BNF(ish) grammar in the spec does not actually have a concept of “a full selector is composed of a series of simple selectors, each of which is composed of multiple atomic selectors”. It just defines a selector as a sequence of `any` tokens, each of which may be followed by any amount of whitespace. The grammar does not make it apparent that some (and only some) of that whitespace will be semantically significant.

As a result, you get lots and lots of compatibility matrices [like this one](https://dev.l-c-n.com/CSS3-selectors/browser-support.php) which check support for various atomic selectors, but only mention in passing that IE&#160;6 does not fully support chaining atomic selectors (as in footnote 9 on that page (and note that it relates to *pseudo*-classes – suggesting that this was a deeper, more general problem in the CSS engine of that browser)).

This means I do not know for a fact that IE&#160;6 is the only problem case.

*However*, there are things I *do* know. Firstly, I have *only* ever seen the lack of support stated for IE&#160;6, never for another browser. I also know for a fact (because I was there at the time) that Gecko and the old Opera engine have supported chained selectors since before IE&#160;6 existed. I know that WebKit has supported them since birth. Likewise for every browser engine out of Microsoft since IE&#160;7.

Adding up these facts, they would seem to cover the entire browser space today. Simplifying just a bit, WebKit essentially means “all of mobile”, and the rest of those engines mean “all of the desktop”. So as far as I can think, the things I know equate to “yes, only IE&#160;6 has ever been affected”.

It’s just unfortunate that I cannot point at a CSS support matrix which shows this categorically.

**Comment by ap** [comment]
> Perhaps you have a really compelling reason why `.blah.yay` is better than `.blah-yay`?

1. For lack of the downside you yourself noted. By using `.blah.yay` and `.bleh.yay` and `.meh.yay`, you can avoid having to configure each Javascript component to tell it that yayness is defined by `.blah-yay` here, `.bleh-yay` there, and `.meh-yay` over there. It’s just all `.yay` as far as the JS is concerned. Yay!

2. As I noted, for `isHidden` it’s likely you’ll want `display: none` everywhere that state appears, regardless of module. Using `isHidden` rather than `blah-isHidden` allows defining that centrally. If that got out of hand, it would create maintenance problems, but if you limit it, it improves things, and not only in the obvious way that you gain a little cleanliness in the stylesheets. It also gives you the opportunity to pick a few states that shall have shared meaning everywhere. Anywhere you see `isHidden`, you have an immediate baseline understanding of what it’s for, independent of context.

That second point is a matter of taste, of course. But the first one is universal.

**Comment by adamsilver** [comment]
@ap Your two comments are excellent so thank you for that. 

I agree that it probably is just IE6. If I had just one person who had to use IE6 trying to access my website, I would want them to be able to access it (unless it was a huge amount of effort, which it rarely is--`hasLayout` anyone?).

> 1. For lack of the downside you yourself noted. By using .blah.yay and .bleh.yay and .meh.yay, you can avoid having to configure each Javascript component to tell it that yayness is defined by .blah-yay here, .bleh-yay there, and .meh-yay over there. It’s just all .yay as far as the JS is concerned. Yay!

> 2. As I noted, for isHidden it’s likely you’ll want display: none everywhere that state appears, regardless of module. Using isHidden rather than blah-isHidden allows defining that centrally. If that got out of hand, it would create maintenance problems, but if you limit it, it improves things, and not only in the obvious way that you gain a little cleanliness in the stylesheets. It also gives you the opportunity to pick a few states that shall have shared meaning everywhere. Anywhere you see isHidden, you have an immediate baseline understanding of what it’s for, independent of context.

Yes both good points. However, as I describe in the Javascript chapter, we can do this with a global state class. We can still avoid "chained" class selectors.

p.s. I agree with you about "chained" as a term. Like you I tried to google it and had little luck.

**Comment by adamsilver** [comment]
Closing, but feel free to comment and I'll reopen.
