### ISSUE TITLE
Minor typographical errors

### ISSUE THREAD

**Issue by mathuin** [adamsilver/maintainablecss.com-jekyll#63]
I enjoyed your site and look forward to applying the principles you discuss on future projects

On the Organisation page, the first sentence has "nad" where "and" is appropriate.

On the FAQs page, the answer to the first question has "your" where "you're" is appropriate.

Thank you for your hard work!

**Comment by adamsilver** [comment]
@mathuin Thanks a lot. Fixed those now.
