### ISSUE TITLE
State Classes and Modifiers

### ISSUE THREAD

**Issue by callmeaponte** [adamsilver/maintainablecss.com-jekyll#66]
First off, great job on putting all of this together. Out of all of the CSS "conventions" I've read through - yours most closely aligns to what I personally use for my projects. With that in mind, I have a few suggestions that you may (or may not) like:

**State**
I no longer use a `module-state` or `module-component-state` naming convention, as I've found that abstracting state into its own `is-*` class makes it easier to reuse:

    .is-active { display: block; }
    .is-inactive { display: none; }

... and if you need to override its behavior for a particular element, you can nest/chain the selector:

    .foo {
        &.is-active { opacity: 1; }
    }

Otherwise you'll end writing dozens of classes that potentially behave the same:

    .foo-isActive { display: block; }
    .foo-isInactive { display: none; }

    .bar-isActive { display: block; }
    .bar-isInactive { display: none; }

    .baz-isActive { display: block; }
    .baz-isInactive { display: none; }

In addition, this helps immensely with my JavaScript. While we should all strive to separate our concerns as much as possible - inevitably there are times when it makes sense to share classes between CSS and JavaScript (particularly when it comes to state). In this case the `is-*` classes mentioned above can be set by JavaScript, to communicate a module's state to the CSS.

**Modifiers**
Personally I prefer double dashes as delimiters. IMO this makes your class names even more semantic. For example, at first glance it's hard to tell if this is a component or a modifier class:

    .related-sidebar { ... }

... whereas by using double dashes, it's immediately clear that you are looking at a modifier class:

    .related--sidebar { ... }

**Comment by adamsilver** [comment]
Hi @callmeaponte 

You make some great points. And in-fact I have already put all of that in the guide here:

- [http://maintainablecss.com/chapters/state/#what-about-reusing-state](http://maintainablecss.com/chapters/state/#what-about-reusing-state); and 
- [http://maintainablecss.com/chapters/javascript/#2-creating-a-global-state-class](http://maintainablecss.com/chapters/javascript/#2-creating-a-global-state-class)

I have also been thinking about that exact problem with the modifier convention. I agree!

I will make an update shortly.

**Comment by adamsilver** [comment]
It's now updated @callmeaponte - thank you.
