### ISSUE TITLE
Different types

### ISSUE THREAD

**Issue by adamsilver** [adamsilver/maintainablecss.com-jekyll#7]
things like -type1 or -someCategory or -colourX

**Comment by driesjanssens** [comment]
First of all, thanks for writing all of this down. I use the same approach as you describe here.

Just my 2 cents: 
- How I usually write it: "<moduleName>[-<componentName>][--<state>] {}" So "-" for components and "--" for states. I think it emphasizes the distinction a bit more.
- The only part where complexity still surfaces is when mixing browser states. For example ":hover". To manage this I append only the styles specific to this state after the component.

Another thing I like to do (but might be a bit too verbose for some) is to add some comments on how to structure the html of the module.

Example:

```
/**
 * Module: Basket
 * Structure::
 * <div class="basket">
 *  <h2 class="basket-title">...</h2>
 *  <div class="basket-item">
 *      <h3 class="basket-productTitle">...</h3>
 *      <form>
 *          <input type="submit" class="basket-removeButton" value="...">
 *      </form>
 *  </div>
* </div>
 */
.basket {}
.basket--state {}

.basket-title {}

.basket-item {}
.basket-item--state {}
.basket:hover .basket-title {}

.basket-productTitle {}

.basket-removeButton {}

```

**Comment by adamsilver** [comment]
Response went funny...

Thanks for your message. I am not averse double dash. Your reasoning is sound :)

For hover, yes `some-selector:hover`.

With regards to the HTML comment: For me it would be to verbose, as you say. Ideally I don't want to maintain two snippets of HTML, and often the HTML contains view logic, so would need to show the different states meaning that not all elements or different elements show depending upon some logic.
