### ISSUE TITLE
Cheatsheet?

### ISSUE THREAD

**Issue by MrMacStripe** [adamsilver/maintainablecss.com-jekyll#70]
Hey Adam, 
thanks for the awesome writeup. As I'm trying to implement it into my workflow I'm wondering if there's some kind of cheatsheet? I'd imagine it as last chapter in the website summarising the content with code examples. 
Cheers, keep up the good work

**Comment by adamsilver** [comment]
Sounds like a great idea, what sort of things would you want to see on
there?
