### ISSUE TITLE
Typo in the Reuse chapter

### ISSUE THREAD

**Issue by LouisWayne** [adamsilver/maintainablecss.com-jekyll#74]
In the chapter 'Reuse', there is a sentence:

`... which if you’re into SASS is exactly what @extends does.`

The word `@extends` should be `@extend`. (reference: [http://sass-lang.com/guide](http://sass-lang.com/guide))

And thanks for sharing the awesome idea.  I love your approach.

**Comment by adamsilver** [comment]
Thanks @LouisWayne - I'll sort it.
