### ISSUE TITLE
Button visibility based on the parent's class

### ISSUE THREAD

**Issue by LouisWayne** [adamsilver/maintainablecss.com-jekyll#75]
Adam,

I have a question about showing buttons based on the parent's class - but I am not sure which approach is more maintainable.  So here is my code:

```
// HTML
<div class="product">
  <button class="product-cancel">Cancel</button>
  <button class="product-add">Add</button>
  <button class="product-edit">Edit</button>
  <button class="product-done">Done</button>
  ...
</div>

// CSS
.product-cancel,
.product-add,
.product-edit,
.product-done {
  visibility: hidden;
}
```

What I want to do is here that I want to show/hide based on the `<div>` element's classes (`product` module's classes).  So I added classes to the `product` module, and now I have:

```
<div class="product product-hasNoProduct product-editDisabled">
  ...
```

And the button visibility logic is:

When `product` module has classes: `hasNoProduct` **and** `editDisabled`, I want to show the button: `product-add`
When `product` module has classes: `hasNoProduct` **and** `editEnabled`, I want to show the buttons: `product-cancel` and `product-done`
When `product` module has classes: `hasProduct` **and** `editDisabled`, I want to show the button: `product-edit`
When `product` module has classes: `hasProduct` **and** `editEnabled`, I want to show the buttons:
`product-cancel` and `product-done`

You get the idea.

However, based on my understanding, it's a big difficult to achieve - I came up with the two solutions:

```
// Solution 1 - use chaining classes
// CSS
.hasNoProduct.editDisabled {
  .product-add {
    visibility: visible;
  }
}
...
```

I don't like this approach because you explicitly mentioned that using chaining classes makes maintaining harder in the *State* section, and I totally agree with you.  So here is my second solution:

```
// Solution 2 - use single verbose state instead of multiple states
// HTML
<div class="product hasNoProductAndEditDisabled">
  ...

// CSS
.hasNoProductAndEditDisabled {
  .product-add {
    visibility: visible;
  }
}
...
```

The solution 2 is using just one state, but it's way too verbose - also I may add another state to the `product` module in the future, which requires me to update all exiting classes.

I could handle button's visibility for each button (i.e. Using classes like `product-cancel product-cancel-hiding`), but I just don't want to.  I really want to show/hide buttons just based on the parent classes (I think that's the simplest solution).

I really like your approach, and I really want to learn more from you.

Please advise - and if you think there is a better way to solve this problem, please let me know.

**Comment by adamsilver** [comment]
I would handle each button individually. You said you didn't like this approach. Can you explain why?

**Comment by LouisWayne** [comment]
It's because if I modify multiple buttons' class one by one for its visibility, this causes *n* times of browser repaint/reflow.  I want to handle the buttons visibility based on single element, which is its parent element (`product` module) so that the browser repaint/reflow happens only once.

Plus, I think it would be simpler in code perspective since I only need to update one element instead of multiple button elements.

Any thoughts?

**Comment by adamsilver** [comment]
If the classes on multiple buttons are updated in one go then I can't see
this causing any issue.

**Comment by LouisWayne** [comment]
I see, since browser repaint will be done **after** JS execution, updating each button is better solution - and also it manipulates the lower elements in the DOM tree, so it's faster.  Thanks for the advice.
