### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by itsnamgyu** [adamsilver/maintainablecss.com-jekyll#76]
Can I post a Korean translation on a blog? — w/ credits of course.

**Comment by itsnamgyu** [comment]
Just read the FAQ 😓 I'll let you know when I'm done..!

**Comment by adamsilver** [comment]
Brill, thank you.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

Thanks!
Adam

Website: adamsilver.io
Twitter: @adambsilver <http://www.twitter.com/adambsilver/>
